<?php

namespace Application\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProdutoRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProdutoRepository extends EntityRepository
{
}
