<!doctype html> 
<html ng-app="app">
 <head>
    <title>ZF2 com AngularJS</title> 
    <meta charset="utf-8" />
    <link href="css/bootstrap.min.css" type="text/css" media="screen" rel="stylesheet" />
    <!--<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.29/angular.min.js"></script>--> 
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js"></script> 
</head>
 <body> 
    <div ng-controller="CtrlApp"> 
        <input type="text" ng-model="nome" />
        <h1>{{nome}}</h1>
    </div>

    <div ng-controller="CtrlAppTeste"> 
        <input type="text" ng-model="nometeste" />
        <h1>{{nometeste}}</h1>
    </div>
    <script>
        var app = angular.module('app', []);

        app.controller('CtrlApp', function ($scope) {
            $scope.nome = "Roberto";
        });

        var CtrlAppTeste = function ($scope) {
            $scope.nometeste = "Roberto de Oliveira";
        }
        app.controller('CtrlAppTeste',CtrlAppTeste);
    </script>
 </body>
 </html>