<!doctype html> 
<html ng-app="myApp">
 <head>
    <meta charset="utf-8" />
    <title>ZF2 com AngularJS</title> 
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    <!--<link href="css/bootstrap.min.css" type="text/css" media="screen" rel="stylesheet" />-->
</head>
 <body> 
    <div id="wrap">
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand">School of Net</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#/categorias">Categorias</a> </li>
                        <li><a href="#/produtos">Produtos</a> </li>
                    </ul>
                </div>
            </div>
        </div>

        <?php echo $this->content; ?>


        <div id="footer">
            <div class="container">
                <p class="text-muted credit">School of Net.</p>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.29/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.29/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.29/angular-resource.min.js"></script>
    <script src="js/angular/app.js"></script>
    <script src="js/angular/controllers.js"></script>
    <script src="js/angular/services.js"></script>
 </body>
 </html>